- name: interfaces module demo
  hosts: R2
  gather_facts: false
  tasks:
######## gathered ##########################
    - name: Interface Config
      cisco.ios.ios_interfaces:
        state: gathered
      register: intf_config

    - name: Print intf config
      ansible.builtin.debug:
        msg:
          - "{{ intf_config.gathered }}"
######## merged ############################

    - name: Interface Config
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet0/0
          - name: GigabitEthernet0/2
            description: new_desc1
            mtu: 1024
            enabled: true
        state: overridden
      register: intf_config

    - name: Print intf config
      ansible.builtin.debug:
        msg:
          - "{{ intf_config }}"
######## rendered ##########################

    - name: Interface Config
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet0/0
          - name: GigabitEthernet0/2
            description: new_desc1
            mtu: 1024
            enabled: true
        state: rendered
      register: intf_config

    - name: Print intf config
      ansible.builtin.debug:
        msg:
          - "{{ intf_config.rendered }}"