---
- name: NTC
  hosts: R2
  gather_facts: false
  tasks:
   - name: Ansible NTC Templates Parse
     ansible.utils.cli_parse:
      command: show version
      parser:
        name: ansible.netcommon.ntc_templates
      set_fact: sh_ver
     register: show_ver_parser

   - name: Print sh_ver
     ansible.builtin.debug:
       msg: 
         - "{{ show_ver }}"
          