---
- name: Configure domain name
  hosts: routers
  gather_facts: false
  tasks:
    - name: Print date and time
      ansible.builtin.debug:
        msg: "{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S')}}"

    - name: Configure domain
      cisco.ios.ios_config:
        lines: ip domain name testdomain.com
        backup: yes
        backup_options:
          dir_path: ./07_ios_config_demo/bkp/{{ inventory_hostname }}/
          filename: "{{ inventory_hostname }}_{{ ansible_ssh_host }}_{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S')}}.txt"
      register: domain_config
    
    - name: Print COmmand Output
      ansible.builtin.debug:
        msg: "{{ domain_config }}"