---
- name: Configure intf name
  hosts: R1
  gather_facts: false
  tasks:
    - name: Config intf
      cisco.ios.ios_config:
        lines:
          - descreption from ansible
          # - ip address 100.3.3.1.255.255.255.0
        parents: interface {{ item }}
      with_items:
       - FastEthernet0/1 
       - FastEthernet1/0
      register: intf_config

    - name: Print Command Output
      ansible.builtin.debug:
        msg: "{{ intf_config }}"